[package]
name = "disk_gym"
version = "0.1.1"
edition = "2021"


[dependencies]
clap = "2.33"
rand = "0.8.3"
indicatif = "0.16"
tokio = { version = "1", features = ["full"] }
log = "0.4"
simple_logger = "1.0"
futures = "0.3.30"